[package]
name = "oxidb"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2024"

[lib]
name = "oxidb_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
tauri = { version = "2.11.1", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = "0.39.0"
tauri-plugin-dialog = "2.7.1"
directories = "6.0.0"
thiserror = "2.0.18"
async-trait = "0.1.89"
tokio = "1.52.2"
uuid = { version = "1.23.1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
